# Generated by Django 2.2.6 on 2019-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(default=None, help_text='微信号', max_length=100, unique=True, verbose_name='微信号'),
            preserve_default=False,
        ),
    ]
