# Generated by Django 2.2.6 on 2019-11-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, help_text='微信号', max_length=100, null=True, unique=True, verbose_name='微信号'),
        ),
    ]
