# Generated by Django 2.2.6 on 2019-11-16 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191108_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(blank=True, default=0, help_text='用户积分换算比例： 1RMB=10积分', null=True, verbose_name='用户积分'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation', models.SmallIntegerField(choices=[(0, '业务充值'), (1, '购物消费'), (2, '系统赠送')], default=1, verbose_name='积分操作类型')),
                ('number', models.IntegerField(default=0, verbose_name='积分数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
                'db_table': 'ly_credit',
            },
        ),
    ]
