# Generated by Django 2.2.6 on 2019-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191114_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexpire',
            name='text',
            field=models.CharField(help_text='课程有效期文本格式', max_length=64, verbose_name='课程有效期文本格式'),
        ),
    ]
