# Generated by Django 2.2.6 on 2019-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191114_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexpire',
            name='timer',
            field=models.IntegerField(help_text='课程有效期', verbose_name='课程有效期(天)'),
        ),
    ]
