# Generated by Django 2.2.6 on 2019-11-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191114_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexpire',
            name='timer',
            field=models.CharField(help_text='课程有效期', max_length=100, verbose_name='课程有效期(天)'),
        ),
    ]
