# Generated by Django 2.2.6 on 2019-11-14 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191114_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='活动名称')),
                ('start_time', models.DateTimeField(help_text='活动的开始时间', verbose_name='活动的开始时间')),
                ('end_time', models.DateTimeField(help_text='活动的结束时间', verbose_name='活动的结束时间')),
            ],
            options={
                'verbose_name': '优惠活动表',
                'verbose_name_plural': '优惠活动表',
                'db_table': 'ly_activity',
            },
        ),
        migrations.CreateModel(
            name='PriceDiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='类型名称')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '课程优惠类型',
                'verbose_name_plural': '课程优惠类型',
                'db_table': 'ly_price_discount_type',
            },
        ),
        migrations.CreateModel(
            name='PriceDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('condition', models.IntegerField(blank=True, default=0, verbose_name='满足优惠的价格条件')),
                ('sale', models.TextField(help_text='\n    0表示免费；<br>\n    *号开头加上浮点数表示折扣价，例如*0.82表示八二折；<br>\n    如果要表示限时满减,则需要使用 原价-优惠价格,例如表示,课程价格大于100,优惠10;大于200,优惠20,格式如下:<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满100-10<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满200-20<br>\n    ', verbose_name='优惠公式')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricediscounts', to='courses.PriceDiscountType', verbose_name='优惠类型')),
            ],
            options={
                'verbose_name': '价格优惠策略',
                'verbose_name_plural': '价格优惠策略',
                'db_table': 'ly_price_discount',
            },
        ),
        migrations.CreateModel(
            name='CourseActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_courses', to='courses.Activity')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prices', to='courses.Course', verbose_name='课程')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_courses', to='courses.PriceDiscount', verbose_name='优惠活动')),
            ],
            options={
                'verbose_name': '课程与优惠活动的关系',
                'verbose_name_plural': '课程与优惠策略的关系',
                'db_table': 'ly_course_activity',
            },
        ),
    ]
