# Generated by Django 2.2.6 on 2019-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_activity_courseactivity_pricediscount_pricediscounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricediscount',
            name='sale',
            field=models.TextField(help_text='\n    0表示免费；<br>\n    *号开头加上浮点数表示折扣价，例如*0.82表示八二折；<br>\n    -号开头加上数值表示减免价，例如-50表示减免50；<br>\n    如果要表示限时满减,则需要使用 原价-优惠价格,例如表示,课程价格大于100,优惠10;大于200,优惠20,格式如下:<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满100-10<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满200-20<br>\n    ', verbose_name='优惠公式'),
        ),
    ]
